### ISSUE TITLE
Crash with Optifine & Optifine forge installed

### ISSUE THREAD

**Issue by BedrockLegends** [jaredlll08/TipTheScales#10]
https://gist.github.com/BedrockLegends/85ca4bd02591665ba63a437a1dd34e8b

Happens when u click on video settings

**Comment by Darkfiend009** [comment]
Can confirm this as well. Mine occurred in 1.16.1

**Comment by Darkere** [comment]
Would be nice if you could reimplement this: 

`OPTIFINE IS NOT SUPPORTED! THE MOD WILL DO NOTHING IF OPTIFINE IS DETECTED!`

for 1.16. Getting a new report every day :/
It is currently crashing instead.

**Comment by jaredlll08** [comment]
Fixed. thanks
