### ISSUE TITLE
[1.15.2] Client Side?

### ISSUE THREAD

**Issue by TheUntamed** [jaredlll08/TipTheScales#11]
Is this mod client side?
Because whenever I try to upload a server file to curse forge it gets rejected because of version 2.0.1 of this mod. Dunno why.

**Comment by jaredlll08** [comment]
Are you saying that curse rejects the server files? Please elaborate what you mean, screenshots will help

**Comment by TheUntamed** [comment]
Thats the message if I try to uploade it:
![Screenshot_1](https://user-images.githubusercontent.com/48363903/80081562-69add080-8553-11ea-96b5-48e006140eda.jpg)

The same file is also in my client package of the modpack and that upload works fine.

**Comment by jaredlll08** [comment]
This is an issue with curseforge, I haven't deleted any files. I have linked them to this issue though, so hopefully they can figure it out
