### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by jaredlll08** [jaredlll08/TipTheScales#13]
Seeing as it is [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and [Modtoberfest](https://modtoberfest.com/), here is a list of things that people could PR.

* Code optimisation
* Really anything that makes sense

**Comment by litoj** [comment]
It would be very nice, if you guys achieved something like the mods Sodium extras or Reeses sodium options did, where they changed the content/organization of video settings.

**Comment by jaredlll08** [comment]
That is out of scope for the project.

The project strictly just adds a slider, I have no interest doing anything more than that

**Comment by litoj** [comment]
I meant rather making the slider working with sodium. So far I couldn't find it with sodium installed.

**Comment by subatomic-olive** [comment]
Where is the slider supposed to be? I don't see it either with sodium. This mod altered sodium's gui scale slider, but it hasn't been updated in a while.

https://www.curseforge.com/minecraft/mc-mods/better-gui-scaling

or I guess you could put your slider in another menu if sodium is installed (maybe in a Mod Menu config gui)

**Comment by jaredlll08** [comment]
Sodium has it's own slider that does the exact same thing (although they lose values, but that is a bug on them).

**Comment by TwiningShiningDawn** [comment]
> Sodium has it's own slider that does the exact same thing (although they lose values, but that is a bug on them).

could you put on the sight saying "Disclaimer: this mod doesn't work with sodium, since both mods adds a GUI Slider, and sodium overrides this mods GUI slider"

**Comment by jaredlll08** [comment]
I don't think it matters, at the end of the day, the user gets to change their gui scale using a slider, it doesn't matter if it is the tip the scales slider or the sodium one.
