### ISSUE TITLE
[1.18.1] Crashes when together with OptiFine.

### ISSUE THREAD

**Issue by Gbergz** [jaredlll08/TipTheScales#17]
Yes I know OptiFine isn't supported. 

But instead of the mod doing nothing as description says. It crashes the game instead.

Forge: 39.0.44
TipTheScales: 5.0.0+1 | https://www.curseforge.com/minecraft/mc-mods/tipthescales/files/3620488

Logs:
https://pastebin.com/dqR5pvtw

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/tipthescales/files/3631825

**Comment by Gbergz** [comment]
Hey thanks btw, it was fixed but now it's causing crashes again.

Tested with only TipTheScales-5.0.3 & Optifine(preview_OptiFine_1.18.1_HD_U_H5_pre5) on forge **39.0.75**
Crash Report: https://gist.github.com/Gbergz/2afd9d6f6cedd4121cfa23167afd2a2c

**Comment by jaredlll08** [comment]
You have tried *without* TipTheScales right?

**Comment by Gbergz** [comment]
> You have tried _without_ TipTheScales right?

Yes ofcourse.

**Comment by jaredlll08** [comment]
Give this a go https://www.curseforge.com/minecraft/mc-mods/tipthescales/files/3649237

**Comment by Gbergz** [comment]
Works now. 👍
