### ISSUE TITLE
Make it compatible with Sodium

### ISSUE THREAD

**Issue by Trackhe** [jaredlll08/TipTheScales#19]
Sodium needs also a fine slider. Would be cool if the mod add that posibillity

**Comment by Gabo075** [comment]
Yes please, we need that

**Comment by jaredlll08** [comment]
not sure I really understand the issue, sodium already has a slider?

![image](https://user-images.githubusercontent.com/5553605/183146603-2bfb3567-fec7-4759-90c3-a34aa1bd61f5.png)

There is an issue where they cap it at `4` though, but they have their own PR open for that, so what is actually being asked here?

**Comment by ChristopherHaws** [comment]
I think they are actually referring to Reese's Sodium Options: https://modrinth.com/mod/reeses-sodium-options
Reese's sodium options causes the slider to jump in increments of 1 instead of letting you set it to fractions.

**Comment by jaredlll08** [comment]
I think it would be better to request that they move to a slider themselves, won't be a fun time if I use a hacky workaround to make their button a slider and then they make it a slider themselves, no idea what would happen, maybe nothing, maybe a crash.

**Comment by Gabo075** [comment]
> not sure I really understand the issue, sodium already has a slider?
> 
> ![image](https://user-images.githubusercontent.com/5553605/183146603-2bfb3567-fec7-4759-90c3-a34aa1bd61f5.png)
> 
> There is an issue where they cap it at `4` though, but they have their own PR open for that, so what is actually being asked here?

No, im guessing the the problem he refers to does not come with the slider that the sodium GUI brings. Instead it to the limited 5x options of the GUIScale of which one is "auto", so technically only 4x. Your mod adds 7x options for the GUI scale, not counting the "auto", allowing to adjust more depending on the screen. It would be great if there was more options for it in the sodium GUI.

**Comment by jaredlll08** [comment]
In that case, there is this open PR for sodium:
https://github.com/CaffeineMC/sodium-fabric/pull/1013

My mod just adds all the available options, sodium arbitrarily limits it to 4 for no reason, with vanilla you get the full 7-8

**Comment by Trackhe** [comment]
It exist a mod for optifine where you can scale like step less. Like a smooth slider with many steps. Like 3.4 or 3.35 are possible so. I can link them if needed.

**Comment by jaredlll08** [comment]
And that is not something that I want to do with the mod right now, it needs way more investigation into how to do it correctly, and make sure it works with other mods (minecraft stores the scale as an int, not a double, so no decimals)

**Comment by jaredlll08** [comment]
I'm going to be closing this due to it not actually being an issue or a feature request that I can reasonably implement.
