### ISSUE TITLE
Error: java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by KianKhadempour** [jaredlll08/TipTheScales#20]
When trying to load Minecraft 1.19.1 with a few mods and TipTheScales-fabric-1.19.1-6.0.3 the game starts loading up and then crashes with exit code -1. 

Here is the crash log:
https://pastebin.com/9n2D1Lt0

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/TipTheScales/commit/ab7d32bfbcc8324a3297b0839a2b2e9a83b3626f
