### ISSUE TITLE
1.19 Compatibility?

### ISSUE THREAD

**Issue by Gabo075** [jaredlll08/TipTheScales#21]

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/tipthescales/files/3920041

Don't see much of a reason to backport to 1.19 right now.

**Comment by Gabo075** [comment]
does it work with 1.19?

**Comment by Gabo075** [comment]
If it doesn't then it would be beneficial as a lot of servers and people do not want to move to 1.19.1 due to the controversial changes made to chat/reports

**Comment by jaredlll08** [comment]
No idea if it works on 1.19, don't see why not.
