### ISSUE TITLE
MC Crash on launch.

### ISSUE THREAD

**Issue by ArrowFX** [jaredlll08/TipTheScales#23]
Don't know what causes the crash but here is the error log!
[crash-2022-11-16_12.20.51-client.txt](https://github.com/jaredlll08/TipTheScales/files/10021100/crash-2022-11-16_12.20.51-client.txt)

(Incase you don't want to download the logs: https://pastebin.com/urhkqCAH)

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/TipTheScales/commit/ebb7c8e64f6aa21177442775935c711742203485
