### ISSUE TITLE
Reverting to auto

### ISSUE THREAD

**Issue by Silvrus** [jaredlll08/TipTheScales#25]
Minecraft: 1.19.2
Forge: 43.2.0
TipTheScales: 1.19.2-6.0.7

This update fixed the crashing that was occurring, but the GUI is reverting to auto again upon game relaunch.

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/TipTheScales/commit/e3fa32234a65e1922f087ecfdc1584233a28e6d2
