### ISSUE TITLE
Could you make a compatability with rubidium - oculus?

### ISSUE THREAD

**Issue by Alexsys** [jaredlll08/TipTheScales#27]
Only one GUI slider appears in the menu settings, the usual GUI
alas the rubidium mod itself doesn't pop up the second gui slider

nor can i find the config file for TipTheScales to modify it itself

any help? :)

**Comment by jaredlll08** [comment]
Are you asking for support as in make it not crash or are you asking for support as in make them work together (put a slider on those mods guis)?

What would you want in the config file?

I also have no idea what you mean by a second gui slider.

**Comment by Alexsys** [comment]
> Are you asking for support as in make it not crash or are you asking for support as in make them work together (put a slider on those mods guis)?
> 
> What would you want in the config file?
> 
> I also have no idea what you mean by a second gui slider.

I might've mistook the actual function of the mod, from what I thought it were.
i thought it adds a second gui slider to adjust the Main stats GUI, and the Inventory GUI separately. Like screenscale mod, which got me to try yours, since screenscale is bugged.

also config,  (from the thought that there was a second slider) to adjust it.
but since there's no second slider nvm that.


if I did mistook it, and the primary function is simply add more sizes, do close the issue
its all good then :)

**Comment by jaredlll08** [comment]
The primary function is to add a slider instead of the button, so you can easily slide to the scale you want, without having to hassle with moving your mouse trying to find the where the button moved to.

On previous versions it added more sizes (before vanilla did).

Unfortunately it is not, and most likely never will be a replacement for screenscale.
