### ISSUE TITLE
Mod straight up does not work.

### ISSUE THREAD

**Issue by zisis912** [jaredlll08/TipTheScales#29]
I have installed the mod, and it appears on ModMenu without any issues. 

When I go to the video settings, GUI scale is a slider, but when i slide it nothing happens and it still has a total of 3 different values, just like before.

The mod description very clearly says it **allows for more options**, yet I have the same 3 options of small, medium, and large just as before.
![image](https://github.com/jaredlll08/TipTheScales/assets/65046191/bf6d155f-2939-49b3-a59b-691bd6596990)

**Comment by jaredlll08** [comment]
It allowed for more options back before Mojang did, currently it doesn't offer any option that vanilla doesn't.

that information is old and I'll update it

When you say nothing happens, does the gui scale change?

Do you have sodium installed?

**Comment by JpnRndr01** [comment]
I gotta ask, is there an actual reason to why the mod is "incompatible" or is it just for the sake of being a pain in the ass?

**Comment by jaredlll08** [comment]
> I gotta ask, is there an actual reason to why the mod is "incompatible" or is it just for the sake of being a pain in the ass?

There is absolutely nothing for me to do to "support" sodium, sodium has their own gui scale slider.
![sodium](https://github.com/jaredlll08/TipTheScales/assets/5553605/b12cb39c-af6d-46eb-9816-8e35fb0f7b48)



I'm going to be closing this issue due to no response.
