### ISSUE TITLE
Crashes when viewing video settings on 1.7.10.

### ISSUE THREAD

**Issue by nycki93** [jaredlll08/TipTheScales#3]
I tested this using the 1.7.10 release of TipTheScales, with no other mods installed. Crashlog: https://paste.ee/p/2Aumk

**Comment by 3TUSK** [comment]
If you have OptiFine: see #2. 

Also, in the CurseForge project page, it is explicitly stated that "OPTIFINE IS NOT SUPPORTED!"

**Comment by jaredlll08** [comment]
This guy isn't issuing optifine, I have already fixed the issue, just need
to release the mod

**Comment by nycki93** [comment]
Thank you!
