### ISSUE TITLE
Support for mods that alter ui

### ISSUE THREAD

**Issue by tayfrm99** [jaredlll08/TipTheScales#33]
rather than working on adding support for mods that alter menu's make it so you can use ingame commands to directly change the scale to a desired value

Command example: `/tts 50` (to set it to 50% scale)

**Comment by jaredlll08** [comment]
Tip the scales doesn't let you change the scale to any arbitrary scale, it only adds a slider instead of a button, so I don't see much use of a command.

If a mod changes the ui to remove the scale options, I would consider that a bug with whatever mod does that.
