### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by sscards55** [jaredlll08/TipTheScales#5]
If the screen size is too small and you go into the options the game will crash, or if the screen is resized too small.

> java.lang.ArithmeticException: / by zero
> 	at com.blamejared.tipthescales.client.GuiNewOptionSlider.func_146119_b(GuiNewOptionSlider.java:57)
> 	at net.minecraft.client.gui.GuiButton.func_191745_a(GuiButton.java:76)
> 	at net.minecraft.client.gui.GuiOptionsRowList$Row.func_192634_a(SourceFile:70)
> 	at net.minecraft.client.gui.GuiListExtended.func_192637_a(SourceFile:25)
> 	at net.minecraft.client.gui.GuiSlot.func_192638_a(GuiSlot.java:420)
> 	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:194)
> 	at net.minecraft.client.gui.GuiVideoSettings.func_73863_a(GuiVideoSettings.java:116)
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:366)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>

**Comment by jaredlll08** [comment]
I believe this is fixed
