### ISSUE TITLE
Some settings missing from video settings menu.

### ISSUE THREAD

**Issue by nycki93** [jaredlll08/TipTheScales#6]
Gui scale is the last button shown on the list. Notably, this means that things like Brightness are missing. I don't remember if I used to have this issue, but it happens even when Tip The Scales is the only mod installed (I'm on 1.7.10, forge 1614.)

**Comment by xJon** [comment]
Caused by this line: https://github.com/jaredlll08/TipTheScales/blob/1.7.10/src/main/java/com/blamejared/tipthescales/client/GuiNewVideoSettings.java#L32

**Comment by jaredlll08** [comment]
I don't even think I can still set up a 1.7.10 workspace anymore.

If someone wants to make a PR to fix this, I'll accept it, but at this point unfortunately this is not going to be fixed.
