### ISSUE TITLE
Limits GUI size to "Auto(0)" and "Small(1)" if window below an arbitrary size

### ISSUE THREAD

**Issue by Targren** [jaredlll08/TipTheScales#7]
Mod Version: 1.12.2-1.0.1, 1.12.2-1.0.3

If the window is below an arbitrary height (in 1.0.1) or height AND width (1.0.3), the "GUI Scale" slider is capped at "Small(1)"  In order to set it to "Normal", I have to expand the window, set it to "Normal(2)", exit the video settings, and then resize the window back to the original size.

**Comment by jaredlll08** [comment]
can you get me a recording / gif of this somehow, just so I can see what is actually going on, since I use the exact same code as vanilla, but just lock out options that don't have an effect...

**Comment by Targren** [comment]
[GIF demonstration](https://imgur.com/a/PBQjAhD)

**Comment by jaredlll08** [comment]
What screensize do you play on?

**Comment by Targren** [comment]
1920x1080, 27"

**Comment by jaredlll08** [comment]
This doesn't make sense then O_o, do you play the game maximized, fullscreen or something else?

**Comment by Targren** [comment]
No, windowed, at or about the size shown in the beginning of the GIF.

**Comment by WyldTV** [comment]
My main streaming PC is 1080p. I started an instance, default resolution on beginning is 720p. The slider for GUI size did not offer a Large option. Maximised the window, and the option was there. If you're restricting options based on current window size, this is suboptimal. Valid settings are valid.

**Comment by jaredlll08** [comment]
The issues aren't related, but both have been addressed, and released on curseforge.
